spring.application.name=college-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/college_database
spring.datasource.username=root
spring.datasource.password=2144Wazid#*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true